alerts-permission: "ag.alerts"
silent-mode: true
decay-per-minute: 0.5

owner:
  uuids: []
  auto-claim:
    enabled: true
    name: "ТвойНик"
    require-online-mode: true
  default-bypass: false

penalties:
  mode: "simulate"       # off | simulate | soft | hard
  pvp-only: true
  soft-scale: 0.75
  hard-scale: 0.15
  min-total-vl-soft: 12
  min-total-vl-hard: 20
  max-ping-ms: 220

setback:
  enabled: true
  max-ping-ms: 220
  cooldown-ms: 400

checks:
  SpeedA:
    ground-sprint: 0.36
    ground-walk: 0.215
    air-sprint: 0.42
    air-walk: 0.30
    speed-effect-per-level: 0.06
    horizontal-margin: 0.03
    streak-to-flag: 2
    add-vl: 1.5
    punish-threshold: 0
    setback: "from"     # from | safe | none

  SpeedB:
    window-ms: 900
    walk-bps: 4.4
    sprint-bps: 5.9
    jump-bps: 7.2
    margin-bps: 0.25
    streak-to-flag: 2
    add-vl: 1.5
    punish-threshold: 0
    setback: "from"

  FlyA:
    max-air-ticks: 16
    hover-threshold-ticks: 5
    streak-to-flag: 3
    add-vl: 1.0
    punish-threshold: 0
    setback: "safe"

  NoFallA:
    min-fall: 3.0
    grace-ms: 450
    streak-to-flag: 2
    add-vl: 2.0
    punish-threshold: 0
    setback: "safe"

  JesusA:
    swim-max-h: 0.30
    surface-max-h: 0.36
    margin: 0.03
    streak-to-flag: 3
    add-vl: 1.0
    punish-threshold: 0
    setback: "from"
    
   NoSlowA:
    blocking-walk: 0.20     # допустимая горизонтальная скорость при блоке щитом
    margin: 0.05
    streak-to-flag: 3
    add-vl: 1.0
    punish-threshold: 0
    setback: "from"

  FastPlaceA:
    window-ms: 1000
    cps-limit: 10           # лимит CPS (за 1с) с запасом для легита
    margin-cps: 1
    streak-to-flag: 2
    add-vl: 1.0
    punish-threshold: 0
    setback: "none"
