alerts-permission: "ag.alerts"
silent-mode: true
decay-per-minute: 0.5

owner:
  uuids: []
  auto-claim:
    enabled: true
    name: "ТвойНик"
    require-online-mode: true
  default-bypass: false

penalties:
  mode: "simulate"       # off | simulate | soft | hard
  pvp-only: true
  soft-scale: 0.75
  hard-scale: 0.15
  min-total-vl-soft: 12
  min-total-vl-hard: 20
  max-ping-ms: 220

setback:
  enabled: true
  max-ping-ms: 220
  cooldown-ms: 400

checks:
  SpeedA:
    ground-sprint: 0.36
    ground-walk: 0.215
    air-sprint: 0.42
    air-walk: 0.30
    speed-effect-per-level: 0.06
    horizontal-margin: 0.05
    streak-to-flag: 3
    add-vl: 1.5
    punish-threshold: 0
    setback: "from"

  SpeedB:
    window-ms: 900
    walk-bps: 4.4
    sprint-bps: 5.9
    jump-bps: 7.6
    margin-bps: 0.40
    streak-to-flag: 2
    add-vl: 1.5
    punish-threshold: 0
    setback: "from"

  FlyA:
    hover-threshold-ticks: 7
    streak-to-flag: 3
    add-vl: 1.0
    punish-threshold: 0
    setback: "safe"

  NoFallA:
    min-fall: 4.0       # безопаснее по ложным
    grace-ms: 450
    streak-to-flag: 2
    add-vl: 2.0
    punish-threshold: 0
    setback: "safe"

  JesusA:
    swim-max-h: 0.30
    surface-max-h: 0.36
    margin: 0.03
    streak-to-flag: 3
    add-vl: 1.0
    punish-threshold: 0
    setback: "from"

  StepA:
    max-step: 0.6
    margin: 0.05
    streak-to-flag: 2
    add-vl: 1.0
    punish-threshold: 0
    setback: "from"

  PhaseA:
    streak-to-flag: 2
    add-vl: 2.0
    punish-threshold: 0
    setback: "safe"

  NoSlowA:
    blocking-walk: 0.20
    margin: 0.05
    streak-to-flag: 3
    add-vl: 1.0
    punish-threshold: 0
    setback: "from"

  FastPlaceA:
    window-ms: 1000
    cps-limit: 10
    margin-cps: 1
    streak-to-flag: 2
    add-vl: 1.0
    punish-threshold: 0
    setback: "none"

  FastBreakA:
    window-ms: 1000
    cps-limit: 8
    margin-cps: 1
    streak-to-flag: 2
    add-vl: 1.0
    punish-threshold: 0
    setback: "none"

  ScaffoldA:
    score-threshold: 6.0
    add-vl: 1.5
    setback: "from"

  TowerA:
    streak-to-flag: 3
    add-vl: 1.0
    setback: "from"

  ReachA:
    base-max: 3.2         # базовая легит дистанция
    ping-coeff: 0.003     # +м на 1 мс
    extra-margin: 0.25
    streak-to-flag: 2
    add-vl: 1.5
    punish-threshold: 0
    setback: "none"

  AutoClickerA:
    window-ms: 3000
    cps-limit: 14
    min-std-ms: 35        # слишком ровные интервалы кликов
    min-samples: 12
    streak-to-flag: 2
    add-vl: 1.0
    punish-threshold: 0
    setback: "none"
