name: AquaGuard
main: dev.aquaguard.AquaGuard
version: 0.3.0
api-version: '1.21'

commands:
  ag:
    description: AquaGuard admin
    usage: /ag <ping|gui|vl|penalties|setback|code|bypass|checks|freeze|reload|whoami>
    permission: ag.admin

permissions:
  ag.admin:
    description: Access to AquaGuard admin commands and GUI
    default: op
  ag.alerts:
    description: See AquaGuard alerts
    default: op
  ag.bypass:
    description: Bypass AquaGuard penalties (damage nerf)
    default: false
